sacc_name: "sacc_Forecasting_Y1_3x2pt_Strawberry.sacc"

analysis_choices:
  z_array: # CCLX Github
    z_start: &z_start 0.0001
    z_stop: &z_stop 3.5
    z_number: &z_number 1000

  ell_array: # Forecasting Github
    ell_start: 20
    ell_stop: 2000
    ell_bins: 20

  cosmo: # Forecasting Github
    Omega_m: &Omega_m 0.3388 # Matter density fraction (dark matter + baryonic).
    A_s: &A_s 1.9019e-9 # Amplitude of scalar perturbations.
    #sigma8: &sigma8 0.807 # Variance of matter density perturbations at 8 Mpc/h.
    n_s: &n_s 0.9493 # Primordial scalar perturbation spectral index.
    Omega_b: &Omega_b 0.04575 # Baryonic matter density fraction.
    h: &h 0.6714 # Hubble constant divided by 100 km/s/Mpc; dimensionless.
    w0: &w0 -1.0 # First order term of dark energy equation.
    wa: &wa 0.0 # Second order term of dark energy equation.
    m_nu: &m_nu 0.1 # Sum of neutrino masses in eV.
    Neff: &Neff 3.044 # Effective number of neutrino species.
    T_CMB: &T_CMB 2.7255 # CMB temperature in K.
    Omega_k: &Omega_k 0.0 # Curvature density fraction.
    mass_split: &mass_split "normal" # Neutrino mass hierarchy.
    extra_parameters:
      camb:
        halofit_version: "mead2020"

  surveys_choices:
    scale_cuts: # Forecasting Github (non-linear)
      lmax: &lmax 2000
      kmax: &kmax 0.2

    fsky: 0.43478091 # Forecating Github Y1   (LSST sky) / (full sky)

    tracers:
      lens:
        alpha: &lens_alpha 0.94 # SRD eq. 5  Y1
        beta: &lens_beta 2.0 # SRD eq. 5  Y1
        z0: &lens_z0 0.26 # SRD eq. 5  Y1
        #sigma_z: &lens_sigma_z 0.03         # Not being used in the pipeline
        delta_z: &lens_delta_z 0.00 # Forecasting Github Y1
        mag_bias: &mag_bias 1.0 # Firecrown default value
        bias: # Forecasting Github Y1  (Paul's code)
          lens0: &lens_bias0 1.23885511
          lens1: &lens_bias1 1.3781005
          lens2: &lens_bias2 1.52472019
          lens3: &lens_bias3 1.67665752
          lens4: &lens_bias4 1.83243479
        ngal: # Forecasting Github Y1  (Paul's code)
          lens0: 2.25
          lens1: 3.098
          lens2: 3.071
          lens3: 2.595
          lens4: 1.998

      src:
        #sigma_z: &src_sigma_z 0.05           # Not being used in the pipeline
        delta_z: &src_delta_z 0.00 # Forecasting Github Y1
        sigma_e: 0.26 # SRD D2.1
        ia: &ia 1.0 # Forecasting Github Y1   Table 1 from 2311.16812
        alpha_z: &alpha_z 0.0 # Forecasting Github Y1  (eta_IA) Table 1 from 2311.16812
        z_piv: &z_piv 0.62 # Value taken from 2311.16812
        alpha_g: &alpha_g 1.0 # Firecrown parameter default value
        ngal: # Forecasting Github Y1  (Paul's code)
          src0: 2.036
          src1: 1.964
          src2: 1.973
          src3: 1.987
          src4: 2.023
        mult_bias: # Forecasting Github Y1
          src0: &src_mult_bias0 1.0e-3
          src1: &src_mult_bias1 1.0e-3
          src2: &src_mult_bias2 1.0e-3
          src3: &src_mult_bias3 1.0e-3
          src4: &src_mult_bias4 1.0e-3

tracer_combinations: # Lens auto and first neighbour cross, all sources and lens-source cross
  lens_lens:
    combinations: [[0, 0], [1, 1], [2, 2], [3, 3], [4, 4]]
    kmax: *kmax
  lens_src:
    combinations: [[0, 2], [0, 3], [0, 4], [1, 3], [1, 4], [2, 4], [3, 4]]
    kmax: *kmax
  src_src:
    combinations:
      [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 3],
        [3, 4],
        [4, 4],
      ]
    lmax: *lmax

redshift_distribution:
  lens: SRD_Y1
  src: SRD_Y1

firecrown_parameters:
  Omega_m: *Omega_m
  A_s: *A_s
  #sigma8: *sigma8
  n_s: *n_s
  Omega_b: *Omega_b
  h: *h
  w0: *w0
  wa: *wa
  m_nu: *m_nu
  Neff: *Neff
  T_CMB: *T_CMB
  Omega_k: *Omega_k

  alphaz: *alpha_z
  z_piv: *z_piv
  ia_bias: *ia

  lens0_bias: *lens_bias0
  lens1_bias: *lens_bias1
  lens2_bias: *lens_bias2
  lens3_bias: *lens_bias3
  lens4_bias: *lens_bias4

  lens0_delta_z: *lens_delta_z
  lens1_delta_z: *lens_delta_z
  lens2_delta_z: *lens_delta_z
  lens3_delta_z: *lens_delta_z
  lens4_delta_z: *lens_delta_z

  src0_delta_z: *src_delta_z
  src1_delta_z: *src_delta_z
  src2_delta_z: *src_delta_z
  src3_delta_z: *src_delta_z
  src4_delta_z: *src_delta_z

firecrown_factories:
  nc_factory:
    per_bin_systematics:
      - type: PhotoZShiftFactory
    global_systematics: []
    include_rsd: false
  wl_factory:
    per_bin_systematics:
      - type: PhotoZShiftFactory
    global_systematics:
      - type: LinearAlignmentSystematicFactory
        alphag: *alpha_g
