analysis_choices:
  z_array:
    z_start: &z_start 0.0001
    z_stop: &z_stop 3.5
    z_number: &z_number 50001
  ell_array:
    ell_start: 20
    ell_stop: 3000
    ell_bins: 21
  cosmo:
    Omega_c: &Omega_c 0.2664315
    Omega_k: &Omega_k 0.0
    sigma8: &sigma8 0.831
    h: &h 0.6727
    n_s: &n_s 0.9645
    Omega_b: &Omega_b 0.0491685
    Neff: &Neff 3.044
    T_CMB: &T_CMB 2.7255
    w0: &w0 -1.0
    wa: &wa 0.0
    m_nu: &mnu 0.0
  surveys_choices:
    lsst:
      scale_cuts:
        lmax: &lmax 3000
        kmax: &kmax 0.201 # 0.3*h
      fsky: 0.4347809097398807
      tracers:
        lens:
          alpha: &lens_alpha 0.94
          beta: &lens_beta 2.0
          z0: &lens_z0 0.26
          sigma_z: &lens_sigma_z 0.03
          delta_z: &lens_delta_z 0.00
          bias:
            lens0: &lens_bias0 1.562362
            lens1: &lens_bias1 1.732963
            lens2: &lens_bias2 1.913252
            lens3: &lens_bias3 2.100644
            lens4: &lens_bias4 2.293210
          ngal:
            lens0: 2.25
            lens1: 3.098
            lens2: 3.071
            lens3: 2.595
            lens4: 1.998
        src:
          sigma_z: &src_sigma_z 0.05
          delta_z: &src_delta_z 0.00
          sigma_e: 0.26
          ngal:
            src0: 2.0
            src1: 2.0
            src2: 2.0
            src3: 2.0
            src4: 2.0
          ia: &ia 0.5
          alpha_z: &alpha_z 0.0
          z_piv: &z_piv 0.62

tracer_combinations:
  - x: lens0
    y: lens0
    kmax: *kmax
  - x: lens1
    y: lens1
    kmax: *kmax
  - x: lens2
    y: lens2
    kmax: *kmax
  - x: lens3
    y: lens3
    kmax: *kmax
  - x: lens4
    y: lens4
    kmax: *kmax
  - x: lens0
    y: src2
    kmax: *kmax
  - x: lens0
    y: src3
    kmax: 0.201
  - x: lens0
    y: src4
    kmax: *kmax
  - x: lens1
    y: src3
    kmax: *kmax
  - x: lens1
    y: src4
    kmax: *kmax
  - x: lens2
    y: src4
    kmax: *kmax
  - x: lens3
    y: src4
    kmax: *kmax
  - x: src0
    y: src0
    lmax: *lmax
  - x: src0
    y: src1
    lmax: *lmax
  - x: src0
    y: src2
    lmax: *lmax
  - x: src0
    y: src3
    lmax: *lmax
  - x: src0
    y: src4
    lmax: *lmax
  - x: src1
    y: src1
    lmax: *lmax
  - x: src1
    y: src2
    lmax: *lmax
  - x: src1
    y: src3
    lmax: *lmax
  - x: src1
    y: src4
    lmax: *lmax
  - x: src2
    y: src2
    lmax: *lmax
  - x: src2
    y: src3
    lmax: *lmax
  - x: src2
    y: src4
    lmax: *lmax
  - x: src3
    y: src3
    lmax: *lmax
  - x: src3
    y: src4
    lmax: *lmax
  - x: src4
    y: src4
    lmax: *lmax

firecrown_parameters:
  Omega_c: *Omega_c
  Omega_k: *Omega_k
  sigma8: *sigma8
  h: *h
  n_s: *n_s
  Omega_b: *Omega_b
  Neff: *Neff
  T_CMB: *T_CMB
  w0: *w0
  wa: *wa
  m_nu: *mnu
  alphaz: *alpha_z
  z_piv: *z_piv
  ia_bias: *ia
  lens0_bias: *lens_bias0
  lens0_delta_z: *lens_delta_z
  lens1_bias: *lens_bias1
  lens1_delta_z: *lens_delta_z
  lens2_bias: *lens_bias2
  lens2_delta_z: *lens_delta_z
  lens3_bias: *lens_bias3
  lens3_delta_z: *lens_delta_z
  lens4_bias: *lens_bias4
  lens4_delta_z: *lens_delta_z
  src0_delta_z: *src_delta_z
  src1_delta_z: *src_delta_z
  src2_delta_z: *src_delta_z
  src3_delta_z: *src_delta_z
  src4_delta_z: *src_delta_z

firecrown_factories:
  nc_factory:
    per_bin_systematics:
      - type: PhotoZShiftFactory
    global_systematics: []
    include_rsd: false
  wl_factory:
    per_bin_systematics:
      - type: PhotoZShiftFactory
    global_systematics:
      - type: LinearAlignmentSystematicFactory
        alphag: 1.0
